#lang eopl

(require "../utils.rkt")

(lambda (x y)
  (+ (f (g x)) (h (j y)))
)

(lambda (x y cont)
  (g x (lambda (val1)
    (f val1 (lambda (val2)
      (j y (lambda (val3)
        (h val3 (lambda (val4)
          (cont (+ val2 val4))
        ))
      ))
    ))
  ))
)

(lambda (x y cont)
  (g x (lambda (val1)
    (j y (lambda (val2)
      (f val1 (lambda (val3)
        (h val2 (lambda (val4)
          (cont (+ val3 val4))
        ))
      ))
    ))
  ))
)

(lambda (x y cont)
  (j y (lambda (val1)
    (h val1 (lambda (val2)
      (g x (lambda (val3)
        (f val3 (lambda (val4)
          (cont (+ val2 val4))
        ))
      ))
    ))
  ))
)

(lambda (x y cont)
  (j y (lambda (val1)
    (g x (lambda (val2)
      (f val2 (lambda (val3)
        (h val1 (lambda (val4)
          (cont (+ val3 val4))
        ))
      ))
    ))
  ))
)
